#!/usr/bin/env bash
# installind nginx 

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
