#!/usr/bin/env bash
# installing nginx 

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow "Nginx HTTP"
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
sudo chmod 777 /var/www/html/index.html
sudo service nginx restart
